### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './data/ml-1m/proc_data/movie_detail.json'

### ISSUE THREAD

**Issue by Ding991105** [LaVieEnRose365/ReLLa#1]
您好！我在使用python get_semantic_embed.py --model_path Vicuna-7B --dataset ml-1m --pooling average时出现以下报错:
FileNotFoundError: [Errno 2] No such file or directory: './data/ml-1m/proc_data/movie_detail.json'
请问这个文件是怎么获得的呢？

**Comment by LaVieEnRose365** [comment]
I think this issue has been resolved.
If you have other questions, feel free to open another issue.
